[package]
name = "cobra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
sexp = "1.1.4"
thiserror = "1.0"

[dev-dependencies]
prettydiff = "0.6.4"